### ISSUE TITLE
¿Eliminar el "Leer más"?

### ISSUE THREAD

**Issue by gvilarino** [PartidoDeLaRed/asamblea#15]
Medio que complica el asunto. Quizás no es 'eliminarlo' pero sí econtrar una forma en que funcione mejor. Ejemplos:
1. Que sólo aparezca si el contenido supera el tamaño del viewport (lógica de cliente).
2. Que sólo aparezca dadas ciertas condiciones como cantidad de párrafos, cantidad de líneas, etc.
3. Que sea una opción en el `compose`.

Igual quitándolo croe que ya ganamos bocha.

**Comment by mjlescano** [comment]
¡Sacarlo a full! También lo queríamos sacar en DemocracyOS.

**Comment by gvilarino** [comment]
Gogogo
